import {
  AlignHorizontalSpaceAround,
  AppWindow,
  AudioLines,
  AudioWaveform,
  BadgeCheck,
  Binary,
  Blend,
  Braces,
  Camera,
  Clock3,
  CloudDownload,
  Code,
  Cpu,
  Crop,
  Dices,
  Eraser,
  File,
  FileArchive,
  FileImage,
  FileMusic,
  FileOutput,
  FileType2,
  FileVideo2,
  Film,
  Fingerprint,
  Files,
  Gauge,
  Globe,
  Grid3X3,
  Image,
  ImageDown,
  Images,
  Link,
  PanelsTopLeft,
  QrCode,
  Regex,
  ScanText,
  Scissors,
  SlidersHorizontal,
  SquareStack,
  SwatchBook,
  Volume2,
  type LucideIcon,
} from "lucide-react";
import type { ToolCategory } from "@/lib/featureFlags";

/** One distinctive glyph per registered tool. Action icons may still repeat elsewhere. */
export const toolIconMap = {
  "video-converter": FileVideo2,
  "audio-converter": AudioLines,
  "video-compressor": Gauge,
  "audio-compressor": SlidersHorizontal,
  "video-trimmer": Scissors,
  "audio-trimmer": AudioWaveform,
  "mp4-to-mp3": FileMusic,
  "volume-booster": Volume2,
  "image-converter": Images,
  "image-compressor": ImageDown,
  "background-remover": Eraser,
  "image-cropper": Crop,
  "png-to-webp": FileImage,
  "pdf-merge": Files,
  "pdf-split": FileOutput,
  "pdf-compressor": FileArchive,
  "pdf-to-word": FileType2,
  ocr: ScanText,
  "url-shortener": Link,
  "qr-generator": QrCode,
  "json-formatter": Braces,
  "base64-encoder": Binary,
  "hash-generator": Fingerprint,
  "website-screenshot": Camera,
  "url-downloader": CloudDownload,
  "uuid-generator": Dices,
  "jwt-decoder": BadgeCheck,
  "regex-tester": Regex,
  "timestamp-converter": Clock3,
  "color-palette": SwatchBook,
  "css-gradient": Blend,
  "box-shadow": SquareStack,
  "flexbox-playground": AlignHorizontalSpaceAround,
  "grid-generator": Grid3X3,
  "favicon-generator": AppWindow,
  "meta-preview": PanelsTopLeft,
} satisfies Record<string, LucideIcon>;

export const categoryIconMap: Record<ToolCategory, LucideIcon> = {
  media: Film,
  image: Image,
  document: File,
  web: Globe,
  dev: Code,
};

export function getToolIcon(toolId: string): LucideIcon {
  return toolIconMap[toolId as keyof typeof toolIconMap] ?? Cpu;
}
